"""P6 AI recommendations: rule-based insights from the live OS loop. LLM rewrite is optional."""
from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from typing import Optional
from zoneinfo import ZoneInfo

from fastapi import APIRouter, Depends, HTTPException

import rbac
from p5 import ad_health, calc_metrics, notify, write_audit

IST = ZoneInfo("Asia/Kolkata")
CLIENT_KINDS = ("ads_health", "ads_budget", "ads_ab", "seo_rank", "web_stage", "clip_idea")
STATUSES = ("open", "accepted", "dismissed")


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def llm_enabled() -> bool:
    return bool((os.environ.get("OPENAI_API_KEY") or "").strip())


def client_insight(row: dict) -> dict:
    return {
        "id": row.get("id"),
        "client_id": row.get("client_id"),
        "kind": row.get("kind"),
        "severity": row.get("severity"),
        "title": row.get("title"),
        "body": row.get("body"),
        "why": row.get("why"),
        "link": row.get("link"),
        "status": row.get("status"),
        "updated_at": row.get("updated_at"),
    }


async def _upsert(db, draft: dict) -> Optional[dict]:
    key = draft["dedupe_key"]
    existing = await db.insights.find_one({"dedupe_key": key}, {"_id": 0})
    if existing:
        if existing.get("status") in ("accepted", "dismissed"):
            return None
        patch = {
            "title": draft["title"],
            "body": draft["body"],
            "why": draft["why"],
            "severity": draft["severity"],
            "link": draft.get("link") or existing.get("link"),
            "action": draft.get("action"),
            "updated_at": _now(),
        }
        await db.insights.update_one({"id": existing["id"]}, {"$set": patch})
        existing.update(patch)
        return existing
    doc = {
        "id": str(uuid.uuid4()),
        "status": "open",
        "created_at": _now(),
        "updated_at": _now(),
        **draft,
    }
    await db.insights.insert_one(doc)
    doc.pop("_id", None)
    return doc


def _clip_from_plan(client_id: str, client_name: str, sections: dict) -> Optional[dict]:
    pillars = str((sections or {}).get("content_pillars") or "").strip()
    offer = str((sections or {}).get("offer") or "").strip()
    audience = str((sections or {}).get("audience") or "").strip()
    if not (pillars or offer):
        return None
    hook_src = (pillars.split("\n")[0] if pillars else audience)[:80]
    hook = f"If you are {hook_src[:60] or client_name}, this is for you."
    body = (offer or pillars)[:400]
    return {
        "client_id": client_id,
        "kind": "clip_idea",
        "severity": "info",
        "title": f"Clip idea for {client_name}",
        "body": f"Hook: {hook}",
        "why": "Built from the approved plan (pillars / offer). Not generated by a language model unless you tap Rewrite.",
        "link": "/dashboard/clip",
        "dedupe_key": f"clip-idea:{client_id}",
        "action": {
            "type": "clip",
            "title": f"{client_name} · {hook_src[:40] or 'Idea'}",
            "hook": hook,
            "body": body,
            "cta": "Message us on WhatsApp to book.",
            "category": "lead_gen",
        },
    }


async def generate_insights(db, user: dict) -> dict:
    q: dict = {}
    rbac.apply_client_query(q, user)
    today = datetime.now(IST).date().isoformat()
    created = 0
    is_client = user.get("role") == "client"

    clients = {c["id"]: c.get("name") or "Client" for c in await db.clients.find(q, {"_id": 0, "id": 1, "name": 1}).to_list(200)}
    ads = await db.ads_campaigns.find(q, {"_id": 0}).to_list(400)
    for row in ads:
        m = calc_metrics(row)
        h = ad_health(row)
        cid = row.get("client_id")
        name = row.get("name") or row.get("platform") or "Campaign"
        if h.get("score") is not None and h["score"] < 50:
            if await _upsert(db, {
                "client_id": cid, "kind": "ads_health", "severity": "action",
                "title": f"{name} needs work (Ad Health {h['score']})",
                "body": "Refresh the creative or pause until the numbers move.",
                "why": "; ".join(h.get("reasons") or []) or "Internal Ad Health is below 50.",
                "link": "/dashboard/performance",
                "dedupe_key": f"ads-health:{row.get('id')}",
                "action": {"type": "task", "title": f"Fix ads: {name}", "brief": "; ".join(h.get("reasons") or []), "department": "marketing", "job_role": "digital_marketer"},
            }):
                created += 1
        if m["budget"] > 0 and m["spent"] > m["budget"] * 1.2:
            if await _upsert(db, {
                "client_id": cid, "kind": "ads_budget", "severity": "important",
                "title": f"{name} is over budget",
                "body": f"Spent ₹{int(m['spent']):,} vs budget ₹{int(m['budget']):,}.",
                "why": "Spend is more than 20% over the typed budget.",
                "link": "/dashboard/ads",
                "dedupe_key": f"ads-budget:{row.get('id')}",
                "action": {"type": "task", "title": f"Cap spend: {name}", "brief": f"Spent {m['spent']} / budget {m['budget']}", "department": "marketing", "job_role": "digital_marketer"},
            }):
                created += 1
        variants = [v for v in (row.get("variants") or []) if (v.get("status") or "running") == "running"]
        if len(variants) >= 2 and not any(v.get("status") == "winner" for v in (row.get("variants") or [])):
            if await _upsert(db, {
                "client_id": cid, "kind": "ads_ab", "severity": "info",
                "title": f"Pick a winner on {name}",
                "body": f"{len(variants)} variants are still running.",
                "why": "A/B only helps once someone marks a winner.",
                "link": "/dashboard/ads",
                "dedupe_key": f"ads-ab:{row.get('id')}",
                "action": {"type": "task", "title": f"Pick A/B winner: {name}", "brief": "Mark the winning variant in Ads.", "department": "marketing", "job_role": "digital_marketer"},
            }):
                created += 1

    seo = await db.seo_items.find(q, {"_id": 0}).to_list(400)
    for row in seo:
        cur, tgt = row.get("current_rank"), row.get("target_rank")
        if cur is None or tgt is None:
            continue
        try:
            cur_n, tgt_n = int(cur), int(tgt)
        except (TypeError, ValueError):
            continue
        if cur_n > tgt_n + 5:
            label = row.get("keyword") or row.get("url") or "SEO"
            if await _upsert(db, {
                "client_id": row.get("client_id"), "kind": "seo_rank", "severity": "important",
                "title": f"{label} is #{cur_n} (target #{tgt_n})",
                "body": "Add evidence and a task, or update the page.",
                "why": "Current rank is more than 5 places worse than target.",
                "link": "/dashboard/seo",
                "dedupe_key": f"seo-rank:{row.get('id')}",
                "action": {"type": "task", "title": f"SEO lift: {label}", "brief": f"Now #{cur_n} → #{tgt_n}\n{row.get('current_state') or ''}", "department": "marketing", "job_role": "seo"},
            }):
                created += 1

    sites = await db.web_sites.find(q, {"_id": 0}).to_list(200)
    for row in sites:
        if row.get("stage") == "client_review" and row.get("client_decision") == "approved":
            if await _upsert(db, {
                "client_id": row.get("client_id"), "kind": "web_stage", "severity": "action",
                "title": f"{row.get('name') or 'Site'} is approved — deploy it",
                "body": "The client said yes. Move the stage to Deployed when it is live.",
                "why": "Client review is approved and still waiting on deploy.",
                "link": "/dashboard/web",
                "dedupe_key": f"web-deploy:{row.get('id')}",
                "action": {"type": "task", "title": f"Deploy {row.get('name') or 'site'}", "brief": "Client approved. Deploy and set stage to Deployed.", "department": "technology", "job_role": "web_developer"},
            }):
                created += 1

    plans = await db.strategies.find({**q, "status": {"$in": ["approved", "implemented"]}}, {"_id": 0}).to_list(80)
    for plan in plans:
        cid = plan.get("client_id")
        idea = _clip_from_plan(cid, clients.get(cid) or "Client", plan.get("sections") or {})
        if idea and await _upsert(db, idea):
            created += 1
        if not is_client and plan.get("status") == "approved":
            if await _upsert(db, {
                "client_id": cid, "kind": "strategy_gap", "severity": "info",
                "title": f"Implement {plan.get('title') or 'the plan'}",
                "body": "Approved but not implemented — tasks may still be missing.",
                "why": "Strategy is approved. Implement creates department tasks from filled sections.",
                "link": "/dashboard/strategy",
                "dedupe_key": f"strategy-impl:{plan.get('id')}",
                "action": {"type": "task", "title": f"Implement: {plan.get('title') or 'plan'}", "brief": "Open Strategy Hub and tap Implement.", "department": "marketing", "job_role": "digital_marketer"},
            }):
                created += 1

    if not is_client:
        tasks = await db.tasks.find(
            {**q, "status": {"$in": ["todo", "in_progress", "in_review", "changes_requested"]}, "deadline": {"$nin": [None, ""]}},
            {"_id": 0, "id": 1, "title": 1, "deadline": 1, "client_id": 1},
        ).to_list(200)
        for t in tasks:
            due = str(t.get("deadline") or "")[:10]
            if due and due < today:
                if await _upsert(db, {
                    "client_id": t.get("client_id"), "kind": "overdue_task", "severity": "action",
                    "title": f"Overdue task: {t.get('title') or 'Task'}",
                    "body": f"Due {due}. Finish it or move the date.",
                    "why": "Open task past its deadline.",
                    "link": "/dashboard/tasks",
                    "dedupe_key": f"insight-task:{t['id']}:{due}",
                    "action": None,
                }):
                    created += 1
        events = await db.calendar_events.find({**q, "status": "approved", "date": {"$lt": today}}, {"_id": 0, "id": 1, "title": 1, "date": 1, "client_id": 1}).to_list(200)
        for ev in events:
            if await _upsert(db, {
                "client_id": ev.get("client_id"), "kind": "overdue_content", "severity": "action",
                "title": f"Publish overdue: {ev.get('title') or 'Post'}",
                "body": f"Approved for {ev.get('date')}. Open the publish queue.",
                "why": "Approved calendar item is past its planned date.",
                "link": "/dashboard/publish",
                "dedupe_key": f"insight-cal:{ev['id']}",
                "action": None,
            }):
                created += 1

    return {"ok": True, "upserted": created, "llm": llm_enabled()}


def _rewrite_clip(action: dict) -> dict:
    key = (os.environ.get("OPENAI_API_KEY") or "").strip()
    if not key:
        raise HTTPException(status_code=400, detail="Rewrite needs OPENAI_API_KEY. Rule-based ideas still work without it.")
    import requests
    prompt = (
        "Rewrite this short-form video idea. Return JSON with keys hook, body, cta. "
        "Keep hook under 12 words, body under 80 words, CTA one line.\n"
        f"Hook: {action.get('hook')}\nBody: {action.get('body')}\nCTA: {action.get('cta')}"
    )
    try:
        r = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={
                "model": os.environ.get("OPENAI_MODEL") or "gpt-4o-mini",
                "temperature": 0.7,
                "messages": [
                    {"role": "system", "content": "You write short-form video scripts for a small Indian agency. JSON only."},
                    {"role": "user", "content": prompt},
                ],
            },
            timeout=25,
        )
        r.raise_for_status()
        text = (((r.json().get("choices") or [{}])[0].get("message") or {}).get("content") or "").strip()
        start, end = text.find("{"), text.rfind("}")
        blob = {}
        if start >= 0 and end > start:
            import json
            blob = json.loads(text[start:end + 1])
        hook = str(blob.get("hook") or action.get("hook") or "")[:200]
        body = str(blob.get("body") or action.get("body") or "")[:2000]
        cta = str(blob.get("cta") or action.get("cta") or "")[:200]
        return {**action, "hook": hook, "body": body, "cta": cta, "rewritten": True}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Rewrite failed: {e}") from e


def create_p6_router(db, *, get_current_user, sanitize_input, logger) -> APIRouter:
    router = APIRouter()

    async def _row(insight_id: str, user: dict) -> dict:
        row = await db.insights.find_one({"id": insight_id}, {"_id": 0})
        if not row:
            raise HTTPException(status_code=404, detail="Recommendation not found")
        rbac.assert_client_access(user, row.get("client_id"))
        return row

    @router.get("/insights")
    async def list_insights(current_user: dict = Depends(get_current_user)):
        rbac.assert_can(current_user, "insights", "read")
        q: dict = {"status": "open"}
        rbac.apply_client_query(q, current_user)
        if current_user.get("role") == "client":
            q["kind"] = {"$in": list(CLIENT_KINDS)}
        else:
            kinds = rbac.insight_kinds_for(current_user)
            if kinds is not None:
                q["kind"] = {"$in": kinds}
        rows = await db.insights.find(q, {"_id": 0}).sort("updated_at", -1).to_list(120)
        if current_user.get("role") == "client":
            rows = [client_insight(r) for r in rows]
        return {"items": rows, "llm": llm_enabled()}

    @router.post("/insights/refresh")
    async def refresh_insights(current_user: dict = Depends(get_current_user)):
        rbac.assert_can(current_user, "insights", "read")
        result = await generate_insights(db, current_user)
        await write_audit(db, current_user, "refresh", "insights", "", f"upserted {result.get('upserted')}")
        return result

    @router.post("/insights/{insight_id}/dismiss")
    async def dismiss_insight(insight_id: str, current_user: dict = Depends(get_current_user)):
        rbac.assert_can(current_user, "insights", "write")
        row = await _row(insight_id, current_user)
        await db.insights.update_one({"id": insight_id}, {"$set": {"status": "dismissed", "updated_at": _now(), "dismissed_by": current_user["id"]}})
        await write_audit(db, current_user, "dismiss", "insights", insight_id, row.get("title") or "")
        return {"ok": True}

    @router.post("/insights/{insight_id}/accept")
    async def accept_insight(insight_id: str, current_user: dict = Depends(get_current_user)):
        rbac.assert_can(current_user, "insights", "write")
        rbac.assert_can(current_user, "tasks", "write")
        row = await _row(insight_id, current_user)
        if row.get("status") != "open":
            raise HTTPException(status_code=400, detail="Already handled")
        action = row.get("action") or {}
        result = {"ok": True, "task_id": None, "clip_id": None}
        if action.get("type") == "clip":
            rbac.assert_can(current_user, "clips", "write")
            clip = {
                "id": str(uuid.uuid4()),
                "client_id": row["client_id"],
                "task_id": None,
                "calendar_event_id": None,
                "title": sanitize_input(action.get("title") or row.get("title") or "Clip idea")[:200],
                "hook": sanitize_input(action.get("hook") or "")[:500],
                "body": sanitize_input(action.get("body") or "")[:4000],
                "cta": sanitize_input(action.get("cta") or "")[:300],
                "seo_keywords": "",
                "category": action.get("category") or "lead_gen",
                "status": "draft",
                "version": 1,
                "locked": False,
                "handed_to": None,
                "created_by": current_user["id"],
                "updated_at": _now(),
                "created_at": _now(),
            }
            await db.clips.insert_one(clip)
            result["clip_id"] = clip["id"]
        elif action.get("type") == "task":
            task = {
                "id": str(uuid.uuid4()),
                "client_id": row["client_id"],
                "owner_id": current_user["id"],
                "title": sanitize_input(action.get("title") or row.get("title") or "Follow up")[:200],
                "brief": sanitize_input(action.get("brief") or row.get("why") or "")[:4000],
                "deadline": None,
                "status": "todo",
                "department": action.get("department") or "marketing",
                "job_role": action.get("job_role"),
                "campaign_id": None,
                "calendar_event_id": None,
                "evidence": [],
                "created_by": current_user["id"],
                "created_at": _now(),
                "updated_at": _now(),
                "insight_id": insight_id,
            }
            await db.tasks.insert_one(task)
            result["task_id"] = task["id"]
        patch = {"status": "accepted", "updated_at": _now(), "accepted_by": current_user["id"]}
        if result.get("task_id"):
            patch["task_id"] = result["task_id"]
        if result.get("clip_id"):
            patch["clip_id"] = result["clip_id"]
        await db.insights.update_one({"id": insight_id}, {"$set": patch})
        await write_audit(db, current_user, "accept", "insights", insight_id, row.get("title") or "")
        await notify(
            db, current_user["id"], "completed",
            f"Accepted: {row.get('title') or 'recommendation'}",
            "Opened as a task or clip.",
            "/dashboard/tasks" if result.get("task_id") else "/dashboard/clip",
            f"insight-accept:{insight_id}",
        )
        return result

    @router.post("/insights/{insight_id}/rewrite")
    async def rewrite_insight(insight_id: str, current_user: dict = Depends(get_current_user)):
        rbac.assert_can(current_user, "insights", "write")
        row = await _row(insight_id, current_user)
        action = row.get("action") or {}
        if action.get("type") != "clip":
            raise HTTPException(status_code=400, detail="Only clip ideas can be rewritten")
        nxt = _rewrite_clip(action)
        await db.insights.update_one(
            {"id": insight_id},
            {"$set": {
                "action": nxt,
                "body": f"Hook: {nxt.get('hook')}",
                "why": "Rewritten with the optional language model. Still a recommendation until you accept.",
                "updated_at": _now(),
            }},
        )
        await write_audit(db, current_user, "rewrite", "insights", insight_id, "")
        return await db.insights.find_one({"id": insight_id}, {"_id": 0})

    async def seed_indexes():
        await db.insights.create_index("client_id")
        await db.insights.create_index("dedupe_key", unique=True)
        await db.insights.create_index("status")

    router.seed_indexes = seed_indexes  # type: ignore
    return router
